modLoader="javafml"
loaderVersion="[37,)"
license="All Rights Reserved"

[[mods]]
modId="zombieawareness"
version="${file.jarVersion}"
displayName="Zombie Awareness"
authors="Corosus"
description='''
Adds sound and smell awareness to mobs
'''
